server:
  port: 8082

spring:
  application:
    name: data-collection 
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic_info?serverTimezone=GMT%2B8
    username: root
    password: qq16281091
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  cloud:
    openfeign:
      client:
        config:
          # 默认配置，适用于所有 FeignClient
          default:
            connectTimeout: 5000
            readTimeout: 30000
            loggerLevel: basic

          # DataServiceClient 专用配置
          # 对应 @FeignClient(contextId = "dataServiceClient")
          dataServiceClient:
            connectTimeout: 5000
            readTimeout: 60000
            loggerLevel: full
  

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  
# FastAPI 任务处理服务地址
# 对应 data-service-client 中：
# @FeignClient(
#   name = "${task-handler.service-name:task-handler}",
#   url = "${task-handler.base-url:http://localhost:8000}"
# )
task-handler:
  service-name: task-handler
  base-url: http://localhost:8000


logging:
  level:
    # 打印 DataServiceClient 的 OpenFeign 请求日志
    com.exchange.platform.data.client.DataServiceClient: DEBUG

    # Spring Cloud OpenFeign 框架日志
    org.springframework.cloud.openfeign: INFO