server:
  port: 8081

spring:
  application:
    name: data-analytics
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    dynamic:
      primary: sys_app_analytics
      strict: false
      grace-destroy: true

      datasource:
        sys_app_analytics:
          url: jdbc:mysql://localhost:3306/sys_app_analytics?serverTimezone=GMT%2B8
          username: root
          password: qq16281091
          driver-class-name: com.mysql.cj.jdbc.Driver
        
        basic_info:
          url: jdbc:mysql://localhost:3306/basic_info?serverTimezone=GMT%2B8
          username: root
          password: qq16281091
          driver-class-name: com.mysql.cj.jdbc.Driver
        
        type_basic_data:
          url: jdbc:mysql://localhost:3306/type_basic_data?serverTimezone=GMT%2B8
          username: root
          password: qq16281091
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password: qq16281091
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 3000ms
  
  cache:
    type: redis
    redis:
      time-to-live: 60000ms
      cache-null-values: false

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/sys_app_analytics?serverTimezone=GMT%2B8
    user: root
    password: qq16281091
    driver-class-name: com.mysql.cj.jdbc.Driver
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.exchange.analytics.entity.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
